# netlify.toml

[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"

# SPA redirect: Redirect all unmatched routes to index.html for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
